trigger:
- main
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.x'

- task: DotNetCoreCLI@2
  displayName: 'Run all tests'
  inputs:
    command: 'test'
    projects: '**/*.sln'
    testRunTitle: 'Run all tests'
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    projects: 'Blog/Blog.csproj'
    command: 'publish'
    configuration: 'Release'
    zipAfterPublish: true

- task: FileTransform@2
  inputs:
    folderPath: '$(Build.ArtifactStagingDirectory)/Blog.zip'
    enableXmlTransform: false
    jsonTargetFiles: '**/appsettings.json'

- task: PublishPipelineArtifact@1
  displayName: 'Publish package to deploy pipeline'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop'